import { ID3Writer } from 'browser-id3-writer';
import { Mp3Track } from '../types';
import { detectSunoMetadata } from './sunoCleaner';

/**
 * Creates a valid minimal MP3 buffer with audio frame headers
 */
function createMinimalMp3Buffer(durationSeconds = 3): ArrayBuffer {
  // A minimal valid MP3 frame sequence (MPEG-1 Layer 3, 128 kbps, 44.1 kHz, stereo)
  // Each frame is 417 bytes. 3 seconds @ 38.28 frames/sec = ~115 frames
  const frameHeader = new Uint8Array([0xFF, 0xFB, 0x90, 0x64]); // MPEG 1 Layer III, 128kbps, 44100Hz, Joint Stereo
  const frameSize = 417; // 144 * bitrate / sampleRate + padding
  const frameCount = Math.max(10, Math.floor(durationSeconds * 38.28));
  
  const totalAudioBytes = frameCount * frameSize;
  const buffer = new Uint8Array(totalAudioBytes);

  for (let i = 0; i < frameCount; i++) {
    const offset = i * frameSize;
    buffer.set(frameHeader, offset);
    // Fill remaining frame bytes with silence pattern
    for (let j = 4; j < frameSize; j++) {
      buffer[offset + j] = 0x00;
    }
  }

  return buffer.buffer;
}

/**
 * Generates sample SVG cover art as a dataUrl / buffer
 */
function createSampleCoverCanvas(albumTitle: string, color1: string, color2: string): { dataUrl: string; buffer: ArrayBuffer } {
  const canvas = document.createElement('canvas');
  canvas.width = 600;
  canvas.height = 600;
  const ctx = canvas.getContext('2d')!;

  // Background Gradient
  const grad = ctx.createLinearGradient(0, 0, 600, 600);
  grad.addColorStop(0, color1);
  grad.addColorStop(1, color2);
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, 600, 600);

  // Decorative circles
  ctx.fillStyle = 'rgba(255, 255, 255, 0.1)';
  ctx.beginPath();
  ctx.arc(300, 300, 220, 0, Math.PI * 2);
  ctx.fill();

  ctx.beginPath();
  ctx.arc(300, 300, 150, 0, Math.PI * 2);
  ctx.fill();

  // Text
  ctx.fillStyle = '#FFFFFF';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.font = 'bold 36px sans-serif';
  ctx.fillText(albumTitle.toUpperCase(), 300, 270);

  ctx.font = '500 22px sans-serif';
  ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
  ctx.fillText('SUNO GENERATION SAMPLE', 300, 330);

  const dataUrl = canvas.toDataURL('image/jpeg', 0.85);

  // Convert canvas to ArrayBuffer synchronously via dataUrl
  const base64Data = dataUrl.split(',')[1];
  const binaryStr = atob(base64Data);
  const len = binaryStr.length;
  const u8 = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    u8[i] = binaryStr.charCodeAt(i);
  }

  return {
    dataUrl,
    buffer: u8.buffer,
  };
}

/**
 * Generates 4 sample MP3 tracks embedded with Suno AI metadata
 */
export function generateSampleSunoAlbum(): Mp3Track[] {
  const sampleData = [
    {
      title: 'Midnight Horizon [Upbeat Synthwave 120bpm] (Suno v3.5)',
      artist: 'Suno AI',
      album: 'Suno Generation Vol. 1',
      genre: 'Suno AI / Electronic',
      year: '2024',
      trackNumber: '1',
      comment: 'Prompt: Melodic 80s synthwave with female vocals. Seed: 981273. https://suno.com/song/12345-abcd',
      lyrics: '[Verse 1]\nNeon lights in the city night\n[Style: Energetic driving bass]\nRunning fast towards the morning light\n[Chorus]\nMidnight horizon calls my name',
      color1: '#8B5CF6',
      color2: '#3B82F6',
    },
    {
      title: '02 - Summer Echoes [Acoustic Folk Pop]',
      artist: 'Suno User #4829',
      album: 'Suno Generation Vol. 1',
      genre: 'Acoustic / AI',
      year: '2024',
      trackNumber: '2',
      comment: 'Model: Suno v3.5 - Prompt: Acoustic guitar strumming with warm vocal harmonies',
      lyrics: '[Verse 1]\nGolden waves upon the sand\n[Guitar Solo]\n[Chorus]\nSummer echoes hand in hand',
      color1: '#F59E0B',
      color2: '#EF4444',
    },
    {
      title: 'Neon Dreams [Chillhop Beats] suno_998123-f3a2',
      artist: 'Generated by Suno',
      album: 'Suno AI Tracks',
      genre: 'Lo-Fi Chill',
      year: '2024',
      trackNumber: '3',
      comment: 'https://suno.com/song/998123-f3a2 uuid: 998123-f3a2-45bc-890d-1234567890ab',
      lyrics: '[Instrumental intro]\n[suno_tag: smooth Rhodes piano]\n[Outro]',
      color1: '#10B981',
      color2: '#06B6D4',
    },
    {
      title: 'Electric Soul (Suno AI v3)',
      artist: 'Suno.ai',
      album: 'Suno Generation Vol. 1',
      genre: 'R&B Soul',
      year: '2024',
      trackNumber: '4',
      comment: 'Suno prompt: Deep funky bassline, soul organ and smooth rhythm',
      lyrics: '[Verse 1]\nFeel the rhythm in my soul\n[Pre-Chorus]\n[Chorus]\nElectric soul takes control',
      color1: '#EC4899',
      color2: '#8B5CF6',
    },
  ];

  return sampleData.map((item, idx) => {
    const rawAudioBuffer = createMinimalMp3Buffer(4);
    const writer = new ID3Writer(rawAudioBuffer);
    const w = writer as any;

    w.setFrame('TIT2', item.title);
    w.setFrame('TPE1', [item.artist]);
    w.setFrame('TALB', item.album);
    w.setFrame('TYER', 2024);
    w.setFrame('TCON', [item.genre]);
    w.setFrame('TRCK', item.trackNumber);
    w.setFrame('COMM', { description: '', text: item.comment, language: 'eng' });
    w.setFrame('USLT', { description: '', lyrics: item.lyrics, language: 'eng' });

    const cover = createSampleCoverCanvas(item.album, item.color1, item.color2);
    w.setFrame('APIC', {
      type: 3,
      data: cover.buffer,
      description: 'Cover',
      mimeType: 'image/jpeg',
    });

    writer.addTag();
    const mp3Blob = writer.getBlob();
    const fileName = `track_${idx + 1}_suno_sample.mp3`;
    const mp3File = new File([mp3Blob], fileName, { type: 'audio/mpeg' });

    const sunoReport = detectSunoMetadata({
      title: item.title,
      artist: item.artist,
      album: item.album,
      comment: item.comment,
      lyrics: item.lyrics,
    });

    return {
      id: 'sample-' + (idx + 1),
      file: mp3File,
      originalFileName: fileName,
      size: mp3Blob.size,
      duration: 4,
      bitrate: 128,
      sampleRate: 44100,
      title: item.title,
      artist: item.artist,
      album: item.album,
      albumArtist: 'Suno AI',
      genre: item.genre,
      year: item.year,
      trackNumber: item.trackNumber,
      comment: item.comment,
      lyrics: item.lyrics,
      coverArt: {
        dataUrl: cover.dataUrl,
        mimeType: 'image/jpeg',
        buffer: cover.buffer,
        width: 600,
        height: 600,
      },
      sunoDetected: sunoReport,
      isCleaned: false,
      isSelected: true,
      audioUrl: URL.createObjectURL(mp3Blob),
    };
  });
}
