import { SunoCleanOptions, Mp3Track } from '../types';

/**
 * Detects whether a track contains Suno or AI generated metadata flags
 */
export function detectSunoMetadata(data: {
  title?: string;
  artist?: string;
  album?: string;
  comment?: string;
  lyrics?: string;
  rawTags?: Record<string, any>;
}): { isSuno: boolean; reasons: string[] } {
  const reasons: string[] = [];
  const { title = '', artist = '', album = '', comment = '', lyrics = '' } = data;

  const sunoRegex = /suno(\.com|\.ai|\s*v\d|\s*user|\s*generation|\s*ai)?/i;
  const sunoUuidRegex = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

  // Check Title
  if (sunoRegex.test(title)) {
    reasons.push('Suno keyword in Title');
  }
  if (/\[.*?(synth|beat|pop|rock|vocal|bpm|v3|v4|suno).*?\]/i.test(title)) {
    reasons.push('Prompt or model tag in Title');
  }
  if (sunoUuidRegex.test(title)) {
    reasons.push('Suno UUID in Title');
  }

  // Check Artist
  if (sunoRegex.test(artist) || /generated by ai/i.test(artist)) {
    reasons.push('Suno or AI keyword in Artist field');
  }

  // Check Album
  if (sunoRegex.test(album) || /suno generation/i.test(album)) {
    reasons.push('Suno in Album name');
  }

  // Check Comments
  if (sunoRegex.test(comment) || /prompt:|style:|seed:|suno\.com/i.test(comment)) {
    reasons.push('Suno prompt / URL / parameters in Comments');
  }
  if (sunoUuidRegex.test(comment)) {
    reasons.push('Suno UUID in Comments');
  }

  // Check Lyrics
  if (/\[suno.*?\]|\[style:.*?\]|\[prompt:.*?\]/i.test(lyrics)) {
    reasons.push('Suno prompt directives in Lyrics');
  }

  return {
    isSuno: reasons.length > 0,
    reasons,
  };
}

/**
 * Clean a track title according to Suno cleaning options
 */
export function cleanTitle(title: string, options: SunoCleanOptions): string {
  let cleaned = title.trim();

  // Remove leading numbers like "01 - ", "01. ", "1. ", "01 "
  if (options.removeLeadingTrackNumbers) {
    cleaned = cleaned.replace(/^(\d{1,3}[\s.\-_]+)+/g, '');
  }

  // Remove Suno bracketed style/prompt/model tags, e.g. "[Upbeat Pop 120bpm]", "[v3.5]", "(Suno v3)"
  if (options.stripTitleBracketedTags) {
    cleaned = cleaned
      .replace(/\[.*?(v3|v4|suno|bpm|synth|pop|rock|vocal|guitar|solo|tempo|prompt).*?\]/gi, '')
      .replace(/\(.*?(v3|v4|suno|bpm|suno ai).*?\)/gi, '')
      .replace(/\[\s*\]/g, '')
      .replace(/\(\s*\)/g, '');
  }

  // Remove Suno UUIDs
  cleaned = cleaned.replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, '');

  // Clean trailing/leading dashes or extra spaces
  cleaned = cleaned.replace(/\s+/g, ' ').replace(/^[\s\-_]+|[\s\-_]+$/g, '').trim();

  // Title Case if selected
  if (options.autoTitleCase && cleaned.length > 0) {
    cleaned = toTitleCase(cleaned);
  }

  return cleaned || title; // fallback to original if completely stripped
}

/**
 * Clean artist name
 */
export function cleanArtist(artist: string, options: SunoCleanOptions): string {
  if (!options.stripSunoArtist) return artist;
  const isSunoArtist = /suno(\.com|\.ai|\s*v\d|\s*user|\s*ai)?/i.test(artist) || /generated by ai/i.test(artist);
  return isSunoArtist ? '' : artist;
}

/**
 * Clean album name
 */
export function cleanAlbum(album: string, options: SunoCleanOptions): string {
  if (!options.stripSunoAlbum) return album;
  const isSunoAlbum = /suno(\.com|\.ai|\s*v\d|\s*generation)?/i.test(album);
  return isSunoAlbum ? '' : album;
}

/**
 * Clean lyrics
 */
export function cleanLyrics(lyrics: string, options: SunoCleanOptions): string {
  if (!lyrics || !options.cleanLyricsPromptTags) return lyrics;

  let cleaned = lyrics;

  // Remove Suno AI prompt tags like [Style: synthpop], [suno_tag:...], [Prompt:...]
  cleaned = cleaned.replace(/\[(style|prompt|model|seed|bpm|suno_tag):.*?\]/gi, '');

  // Remove empty lines or multiple consecutive blank lines
  cleaned = cleaned
    .split('\n')
    .map(line => line.trim())
    .filter((line, idx, arr) => line.length > 0 || (idx > 0 && arr[idx - 1].length > 0))
    .join('\n');

  return cleaned.trim();
}

/**
 * Auto Title Case helper function
 */
export function toTitleCase(str: string): string {
  const smallWords = /^(a|an|and|as|at|but|by|en|for|if|in|nor|of|on|or|per|the|to|v\.?|vs\.?|via)$/i;

  return str.replace(/([^\s:\-_"'(]+)/g, (match, word, index) => {
    if (
      index > 0 &&
      index + word.length < str.length &&
      smallWords.test(word) &&
      str.charAt(index - 2) !== ':' &&
      str.charAt(index - 1) !== '-'
    ) {
      return word.toLowerCase();
    }
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  });
}
